export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const REGISTER_USER = "REGISTER_USER"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_TO_CART = "DELETE_TO_CART"
export const ADD_GUEST = "ADD_GUEST"
export const UPDATE_TO_CART = "UPDATE_TO_CART"
export const GET_ALL_ITEMS = "GET_ALL_ITEMS"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS"
export const GET_USER_ORDER = 'GET_USER_ORDER'
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS'
export const CHANGE_ROLL = "CHANGE_ROLL"
export const API_URL = 'https://desarrollo-back.herokuapp.com'
// export const API_URL = 'http://localhost:8081'

